### ISSUE TITLE
The polling doesn't stop after unsubscribe

### ISSUE THREAD

**Issue by demiro** [jiayihu/rx-polling#1]
So, I have this setup:

`private _pollingSub$: Subscription = new Subscription();`

later on in the code

```
const request$ = this.scoreService.getMatchScore(match);
const interval = 5000;
 this._pollingSub$ = polling(request$, {interval: interval }).subscribe(handleResponse);
```

and bit more on
`this._pollingSub$.unsubscribe();`

oddly when I invoke unsubscribe, the polling is still happening.
the log soon after:
`console.log(this._pollingSub$);`

produces:

```
closed:true
destination:SafeSubscriber
isStopped:true
syncErrorThrowable:false
syncErrorThrown:false
syncErrorValue:null
_parent:null
_parents:null
_subscriptions:null
__proto__:Subscription
```

**Comment by jiayihu** [comment]
Could you pass the source of `getMatchScore`? Are you sure it returns a cold Observable?
