### ISSUE TITLE
chrome devTools  Performance Monitor js EventListener continuous increase

### ISSUE THREAD

**Issue by huangzhiyong123456** [jiayihu/rx-polling#29]
chrome devTools  Performance Monitor js EventListener continuous increase

**Comment by jiayihu** [comment]
`fromEvent` is used and returned only once from the function: https://github.com/jiayihu/rx-polling/blob/master/index.ts#L77

So it's not possible that it creates new event listeners alone. Please check your code and assess if you're recreating the `polling` Observable multiple times without unsubscribing/closing the previous one

**Comment by huangzhiyong123456** [comment]
https://jiayihu.github.io/rx-polling/demo/

**Comment by huangzhiyong123456** [comment]
https://jiayihu.github.io/rx-polling/demo/
![D904A1B6-F4AF-45A2-85B3-673476B9B4C1](https://user-images.githubusercontent.com/69354677/206336545-7af293bf-37ae-4df7-8cfa-540b2bcdde49.png)

On the example, open chrome devTools Performance, js EventListener increases by 4 each time

**Comment by huangzhiyong123456** [comment]
> `fromEvent`仅从函数中使用和返回一次： https: [//github.com/jiayihu/rx-polling/blob/master/index.ts#L77](https://github.com/jiayihu/rx-polling/blob/master/index.ts#L77)
> 
> 所以它不可能单独创建新的事件监听器。请检查您的代码并评估您是否在`polling`不取消订阅/关闭前一个的情况下多次重新创建 Observable

https://jiayihu.github.io/rx-polling/demo/
![image](https://user-images.githubusercontent.com/69354677/206994275-38cb7149-0e84-4098-b635-8e09cb906fac.png)


例子上，打开chrome devTools Performance，js EventListener每次增加4

**Comment by huangzhiyong123456** [comment]
> `fromEvent` is used and returned only once from the function: https://github.com/jiayihu/rx-polling/blob/master/index.ts#L77
> 
> So it's not possible that it creates new event listeners alone. Please check your code and assess if you're recreating the `polling` Observable multiple times without unsubscribing/closing the previous one

https://jiayihu.github.io/rx-polling/demo/
![image](https://user-images.githubusercontent.com/69354677/207792476-98c97464-cdaf-483a-ba66-1330eb2dd503.png)

For example, open chrome devTools Performance, js EventListener increases by 4 each time
