### ISSUE TITLE
Error Exporting Polling

### ISSUE THREAD

**Issue by jerrin92** [jiayihu/rx-polling#4]
Tried configuring rx-polling in angular. However, I am receiving the following error message after starting the angular service

`ERROR in /Users/jerkatta/Sites/HPCDashboard/src/app/alexa/alexa.component.ts (7,10): Module '"/Users/jerkatta/Sites/HPCDashboard/node_modules/rx-polling/lib/index"' has no exported member 'polling'.`

The import statement is `import { polling } from 'rx-polling';` Right now that is the only line of code related to rx-polling in my component

**Comment by jiayihu** [comment]
It's a default import, not named: `import polling from 'rx-polling';`
