### ISSUE TITLE
Error with error count

### ISSUE THREAD

**Issue by tpdi** [jiayihu/rx-polling#5]
When 'attempts' is high enough (> 3 or 4), errorCount gets reset and polling never calls error.

Note that I'm using fetch, not Observer.ajax, which may change how polling works:
```
   const source = Observable.create((observer) => {
      fetch('http://somesitethatdoesntexist/somepage')
// we should get net::ERR_NAME_NOT_RESOLVED in Chrome
        .then(j => observer.next(j))    // we won't call complete
        .catch(e => observer.error(e)); // incredibly, .catch(observer.error); causes errors
    });

    polling(source, { interval: this.pollingInterval, attempts: 9 })
      .subscribe(
        (res) => console.log(res),
        (error) => {
          // The Observable will throw if it's not able to recover after N attempts
          // By default it will attempt 9 times with an exponential delay between attempts.
          throw error;
        });
```

Your code, I just added a console.log which shows the reseting of errorCount:

```
          .retryWhen((errors$) => {
            return errors$
              .scan(function (errorCount, err) {
                // If already tempted too many times don't retry
                console.log('scan', errorCount, allErrorsCount, lastRecoverCount);
                if (errorCount >= options.attempts)
                  throw err;
                return errorCount + 1;
              }, 0)

```

<img width="466" alt="screen shot 2017-10-08 at 9 11 54 pm" src="https://user-images.githubusercontent.com/1552229/31325028-7e0675c6-ac6d-11e7-9824-a46481518258.png">

**Comment by jiayihu** [comment]
Thanks for reporting but I could not reproduce your issue with the code you provided, `errorCount` was not reset. For the `errorCount` to reset it probably means that you changed tab, maybe that's the problem. I see no issue with your implementation of `fetch`.

Nevertheless I found that `errorCount` was not implemented correctly and resetted **after a recover**. The fix in available in `0.2.3`, maybe that could resolve your issue too.
