### ISSUE TITLE
Update to rxjs 6

### ISSUE THREAD

**Issue by Razzeee** [jiayihu/rx-polling#7]

**Comment by philjones88** [comment]
This is a blocker to those who use this with Angular. Stops from upgrading to v6 of Angular.

**Comment by Razzeee** [comment]
I was able to migrate the code itself quiet easily, but the tests quiet complicated due to some rxjs changes. I commented some out as I wasn't able to commit otherwise.

Maybe it helps to speed up this issue somehow.
https://github.com/Razzeee/rx-polling/tree/update-rxjs-6

**Comment by philjones88** [comment]
I hit a similar road block where it override the timer with a mock (got to 8/10 tests passing)

I suspect they need rewriting the new TestScheduler stuff?

**Comment by jiayihu** [comment]
Sorry guys, I don't have currently the time to work on the fix but I'll happily review and merge any PR!

**Comment by Razzeee** [comment]
@philjones88 exactly the problem I had and wasn't able to find any docs on that at all.

**Comment by jiayihu** [comment]
Good news, I've had some time today to update the code and tests to RxJS6. Now peerDependencies should accept any version of rxjs >= 5.5. Give it a try with the new version `1.0.0` and let me know if everything is fine now!

**Comment by Razzeee** [comment]
Seems to work for me. Thank you!
